spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BankingApplication
    username: postgres
    password: 2551
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update